before_script:
  - whoami
  - sudo docker --version
  - pwd; ls -la

stages:
  - build
  - deploy_staging
  - deploy

build1:
  tags: 
    - production1
    - coursera-xtermjs
  stage: build
  script: 
    - echo "Building the app in staging"
    - ./build-test

deploy_staging1:
  tags: 
    - production1
    - coursera-xtermjs
  stage: deploy
  script:
    - echo "copying new version of git-remote and student homedir into place"
    - sudo rm -rf /srv/persistent-data/gradedirs/grader-monitoring-user/*
    - sudo rm -rf /srv/persistent-data/homedirs/monitoring-user/*
    - sudo cp -R template-student-homedir/* /srv/persistent-data/homedirs/monitoring-user/
    - sudo cp -R template-student-homedir/.bashrc /srv/persistent-data/homedirs/monitoring-user/
    - sudo cp -R template-student-homedir/.emacs /srv/persistent-data/homedirs/monitoring-user/
    - sudo chown -R azureuser:azureuser /srv/persistent-data/homedirs/monitoring-user/
    - sudo rm -rf /srv/persistent-data/git-remotes/monitoring-user/*
    - sudo cp -R template-student-git-remote/* /srv/persistent-data/git-remotes/monitoring-user/
    - sudo chown -R azureuser:azureuser /srv/persistent-data/git-remotes/monitoring-user/
    - sudo chmod -R uog+rwX /srv/persistent-data/git-remotes/monitoring-user/
    - sudo chown 1001:1001 /srv/persistent-data/git-remotes/monitoring-user/passed.*
    - sudo chmod 600 /srv/persistent-data/git-remotes/monitoring-user/passed.*
    - echo "Deploy to staging server"
    - ./run-test-instance
  environment:
    name: staging
  only:
  - staging


deploy_production1:
  tags: 
    - production1
    - coursera-xtermjs
  stage: deploy
  script:
    - echo "Building the production app"
    - ./build-production
    - echo "Copy the git-remote and homedir templates into place for all users" 
    - ./copy-gitremote-and-homedir
    - echo "Deploy to production server"
    - cd /srv/persistent-data/docker-scripts; ./run-everything
  environment:
    name: production
  only:
  - master

